In [1]:
import numpy as np

给定一个随机矩阵（元素值在[-5, 5]范围内），一次调整一个元素值（加1），使得其行列式为目标值则胜利，行列式的绝对值超过阈值则失败。

如果随机矩阵的行列式刚好为目标值，则保存这个随机矩阵，并重新生成一个随机矩阵。

给定一个nxn的0矩阵，一次调整一个元素值（加1），使得其行列式为1则胜利，行列式的绝对值大于1则失败

In [9]:
n_dims = 2
target = 1

data = np.zeros((n_dims,n_dims))

det_data = np.linalg.det(data)

print(data)
print(det_data)

[[0 0]
 [0 0]]
0.0


In [3]:
# n_dims = 2
# max_num = 5
# target = 1
# threshold = 1 #n_dims * max_num ** n_dims
# data = np.random.randint(-max_num,max_num,size=(n_dims,n_dims))
# print(data)
# print(int(np.linalg.det(data)))
# print(threshold)

In [93]:
class Net:
    def get_value(self,data):
        return 0.
    
    def get_prior_prop(self,data,action):
        return 0.

    pass

class MCTS:
    def __init__(self,data):
        self.net = Net()
        # 节点信息
        self.data = data # 实体的数据表示
        self.shape = data.shape
        self.num_layer = 0 # 层数
        self.status = 0 # 0 表示叶子节点，1 表示未完全展开节点， 2表示完全展开节点
        self.label = self.is_done() # 是否为最终节点（可以判断胜负的节点）
        self.value = self.net.get_value(self.data) # （p, v） = f_theta(data) 公式中的v，当前玩家的胜率
        
        # 边信息
        self.action = None
        self.prior_prop = self.net.get_prior_prop(self.data,self.action)
        self.num_visited = 0
        self.cum_value = 0
        self.average_value = 0
        
        # 树信息
        self.parent = None
        self.children = []
     
    def is_done(self):
        return False
    
    def select(self):
        pass
    
    def expand(self):
        ex_node_data = []
        for i in range(self.shape[0]):
            for j in range(self.shape[1]):
                node_data = self.data.copy()
                node_data[i,j] += 1
                ex_node_data.append(node_data)
                
        
        
    
    def evaluate(self):
        pass
    
    def backup(self):
        pass
    
    def play(self):
        pass
        
tree = MCTS()
tree.cum_value

0

In [4]:
a = np. zeros((2,2))

In [5]:
b = a.copy()

In [6]:
b[1,1] = 2

In [7]:
a

array([[0., 0.],
       [0., 0.]])

In [8]:
b

array([[0., 0.],
       [0., 2.]])

In [ ]:
tree.